# Generated by Django 4.0.2 on 2022-03-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('description', models.TextField()),
                ('college', models.CharField(max_length=255, null=True)),
                ('university', models.CharField(max_length=255, null=True)),
                ('current_company', models.CharField(max_length=255, null=True)),
                ('hobbies', models.TextField()),
            ],
        ),
    ]
